Bump azure-pipelines-test-container to v4.0.1
ansible/azure-pipelines-test-vm pull request #17
Opened 2023-05-31 15:27 UTC by webknjaz

This patch updates the test container used in CI to the new v4 that defaults to using Python 3.10 and is based on Ubuntu 22.04 Jammy[[1]].

[1]: https://github.com/ansible/azure-pipelines-test-container/pull/17

Refs:
* https://github.com/ansible/ansible/issues/80424
* https://github.com/ansible/azure-pipelines-test-container/pull/17
* https://github.com/ansible/ansible/pull/80916

2023-05-31 16:28 UTC, mattclay requested changes

2023-05-31 16:28 UTC, mattclay commented on lookup_plugins/annotated_pull_commands.py
> +        'quay.io/ansible/azure-pipelines-test-container:4.0.1',
Add the new image instead of replacing the old one. We'll retire version 3.0.0 later when it's no longer in use.

2023-05-31 16:45 UTC, webknjaz commented on lookup_plugins/annotated_pull_commands.py
> +        'quay.io/ansible/azure-pipelines-test-container:4.0.1',
Done! Marking the thread as resolved.

2023-05-31 16:46 UTC, mattclay approved these changes

2023-05-31 16:46 UTC, webknjaz commented
@mattclay FYI I don't have a `Merge` button here.

2023-05-31 16:52 UTC, mattclay commented
I almost forgot, there's another step to update the template, which should be included in this PR:

https://github.com/ansible/azure-pipelines-test-vm#update-the-template

2023-06-05 16:11 UTC, mattclay approved these changes

2023-06-05 17:30 UTC, webknjaz commented
@mattclay would you merge this?

2023-06-05 17:40 UTC, merged